No AMD GPU software in 2026.06 (yet)

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -93,12 +93,12 @@ jobs:
           ( module load EESSI/2025.06 && module load EasyBuild/5 && module load EESSI-extend && python scripts/generate_data_files.py --eessi-version=2025.06 ) &
           pid1=$!
           # then 2026.06 for EB 5 (does not have EB4)
-          export EESSI_ACCELERATOR_TARGET_OVERRIDE="accel/amd/gfx1200"
-          ( module load EESSI/2026.06 && module load EasyBuild/5 && module load EESSI-extend && python scripts/generate_data_files.py --eessi-version=2026.06 ) &
-          pid2=$!
+          #export EESSI_ACCELERATOR_TARGET_OVERRIDE="accel/amd/gfx1200"
+          #( module load EESSI/2026.06 && module load EasyBuild/5 && module load EESSI-extend && python scripts/generate_data_files.py --eessi-version=2026.06 ) &
+          #pid2=$!
           fail=0  # initialise
           wait $pid1 || fail=1
-          wait $pid2 || fail=2
+          #wait $pid2 || fail=2
           if [ $fail -ne 0 ]; then
             echo "One or more jobs failed (at least job $fail)"
             exit 1
