Catch failures in background jobs

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -40,14 +40,23 @@ jobs:
           # First do 2023.06 for EB 4
           export EESSI_ACCELERATOR_TARGET_OVERRIDE="accel/nvidia/cc80"  # Stick to 8.0 for EB4 as options for 9.0 set by EESSI-extend are not understood there
           ( module load EESSI/2023.06 && module load EasyBuild/4 && module load EESSI-extend && python scripts/generate_data_files.py --eessi-version=2023.06 ) &
+          pid1=$!
           # then 2023.06 for EB 5
           export EESSI_ACCELERATOR_TARGET_OVERRIDE="accel/nvidia/cc90"
           ( module load EESSI/2023.06 && module load EasyBuild/5 && module load EESSI-extend && python scripts/generate_data_files.py --eessi-version=2023.06 ) &
+          pid2=$!
           # then 2025.06 for EB 5 (does not have EB4)
           export EESSI_ACCELERATOR_TARGET_OVERRIDE="accel/nvidia/cc90"
           ( module load EESSI/2025.06 && module load EasyBuild/5 && module load EESSI-extend && python scripts/generate_data_files.py --eessi-version=2025.06 ) &
+          pid3=$!
+          wait $pid1 || fail=1
+          wait $pid2 || fail=2
+          wait $pid3 || fail=3
+          if [ $fail -ne 0 ]; then
+            echo "One or more jobs failed (at least job $fail)"
+            exit 1
+          fi
           # Merge all these results together
-          wait
           python scripts/merge_data_files.py out.yaml eessi*.yaml
           mv out.yaml docs/data/eessi_software_metadata.yaml
           # Generate json data files and markdown index/description for them
