Make CI a bit more challenging

diff --git a/.github/workflows/prs.yml b/.github/workflows/prs.yml
--- a/.github/workflows/prs.yml
+++ b/.github/workflows/prs.yml
@@ -31,16 +31,50 @@ jobs:
             export EESSI_DEBUG_INIT=1
             # Set CPU override for the stack to query
             export EESSI_ARCHDETECT_OPTIONS_OVERRIDE="x86_64/intel/icelake"
-            # Set GPU overrides for the stack to query (we have no GPU, so also override the GPU check)
-            export EESSI_ACCELERATOR_TARGET_OVERRIDE="accel/nvidia/cc90"
-            export EESSI_OVERRIDE_GPU_CHECK=1
             module load EESSI/2023.06
             module load EasyBuild/5
             module load EESSI-extend
             python scripts/generate_data_files.py --eessi-version=2023.06
           ) &
+          pid1=$!
+          # then 2025.06 for EB 5 with AMD accelerators (does not have EB4)
+          (
+            module --force purge
+            export EESSI_DEBUG_INIT=1
+            # Set CPU override for the stack to query
+            export EESSI_ARCHDETECT_OPTIONS_OVERRIDE="x86_64/intel/icelake"
+            # Set GPU overrides for the stack to query (we have no GPU, so also override the GPU check)
+            export EESSI_ACCELERATOR_TARGET_OVERRIDE="accel/amd/gfx1200"
+            export EESSI_OVERRIDE_GPU_CHECK=1
+            module load EESSI/2025.06
+            module load EasyBuild/5
+            module load EESSI-extend
+            python scripts/generate_data_files.py --eessi-version=2025.06
+          ) &
+          pid2=$!
+          # then 2025.06 for EB 5 with NVIDIA accelerators (does not have EB4)
+          (
+            module --force purge
+            export EESSI_DEBUG_INIT=1
+            # Set CPU override for the stack to query
+            export EESSI_ARCHDETECT_OPTIONS_OVERRIDE="x86_64/intel/icelake"
+            # Set GPU overrides for the stack to query (we have no GPU, so also override the GPU check)
+            export EESSI_ACCELERATOR_TARGET_OVERRIDE="accel/nvidia/cc80"
+            export EESSI_OVERRIDE_GPU_CHECK=1
+            module load EESSI/2025.06
+            module load EasyBuild/5
+            module load EESSI-extend
+            python scripts/generate_data_files.py --eessi-version=2025.06
+          ) &
+          pid3=$!
           # Merge all these results together
-          wait
+          wait $pid1 || fail=1
+          wait $pid2 || fail=2
+          wait $pid3 || fail=3
+          if [ $fail -ne 0 ]; then
+            echo "One or more jobs failed (at least job $fail)"
+            exit 1
+          fi
           module reset
           module load EESSI-extend  # Loads EasyBuild and we need that for our merge scripts
           python scripts/merge_data_files.py out.yaml eessi*.yaml
